name: UzlsFour
options:
  developmentLanguage: en
  generateEmptyDirectories: true
targets:
  UzlsFour:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: App
      - path: Game
      - path: Shaders
    resources:
      - path: Resources/levels/level_001.json
      - path: Resources/levels/level_002.json
      - path: Resources/levels/level_003.json
    preBuildScripts:
      - name: Copy Level Files
        script: |
          mkdir -p "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/levels"
          cp "${SRCROOT}/Resources/levels"/*.json "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/levels/"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.uzls.four
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: 6.0
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIStatusBarHidden: YES
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_UIInterfaceOrientation: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
